### ISSUE TITLE
Empty row throws a server error

### ISSUE THREAD

**Issue by cappaulo** [valdisiljuconoks/TechFellow.ScheduledJobOverview#8]
We have an empty error in the scheduled job overview list. Don't know where it comes from but when clicking the "details" button it throws an exception. Please see attached images.
![empty-row](https://cloud.githubusercontent.com/assets/14766310/23455942/cd386a78-fe71-11e6-9fd7-fbf0a8300569.PNG)
![server-error](https://cloud.githubusercontent.com/assets/14766310/23455948/d16224e0-fe71-11e6-9458-1d6147007053.png)

**Comment by valdisiljuconoks** [comment]
Interesting. Some odd records in tblPlugIn table? I can make sure that these records either don't show up in the list, or not clickable.

**Comment by cappaulo** [comment]
Haven't checked. Is that the only table this add-on talks to?

**Comment by valdisiljuconoks** [comment]
Nop. It uses `PlugInLocator.Search()` and `IScheduledJobRepository`. But as far as I remember, if job is not run yet, it might not be registered in `tblScheduledItem` table.

**Comment by valdisiljuconoks** [comment]
Wait for `3.1.1` on [nuget](http://nuget.episerver.com/en/OtherPages/Package/?packageId=TechFellow.ScheduledJobOverview) and see if that fixes the issue.

Thx!

**Comment by cappaulo** [comment]
Will do. Thank you.

**Comment by valdisiljuconoks** [comment]
EPiServer v10, right?

**Comment by cappaulo** [comment]
Yes, correct.

**Comment by valdisiljuconoks** [comment]
Package is out, can you check on your project?

**Comment by valdisiljuconoks** [comment]
close?

**Comment by cappaulo** [comment]
I believe the last two latest version require some newer version of epi core/ui/framework which is not possible for us to install at the moment thus we cannot test this latest hotfix.

**Comment by valdisiljuconoks** [comment]
Ok, sad.

Which version of Epi and plugin you are using? Might release patch for that.

**Comment by cappaulo** [comment]
<package id="TechFellow.ScheduledJobOverview" version="3.0.0" targetFramework="net461" />
<package id="EPiServer.Framework" version="10.2.0" targetFramework="net461" />
<package id="EPiServer.CMS.Core" version="10.2.0" targetFramework="net461" />
<package id="EPiServer.CMS.UI" version="10.2.0" targetFramework="net461" />
<package id="EPiServer.CMS.UI.Core" version="10.2.0" targetFramework="net461" />

**Comment by valdisiljuconoks** [comment]
@cappaulo are you still stick with 10.2 epi version?

**Comment by cappaulo** [comment]
yes, still using 10.2.

**Comment by valdisiljuconoks** [comment]
@cappaulo see if 3.0.1 fixes the issue.
